server:
  port: 8080


# springBoot 2.0 之后 配置url时需要用jdbc-url ,不然多数据源时找不到URL
spring:
    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true

    datasource:
      primary:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        name: test
        jdbc-url: jdbc:mysql://10.10.13.125:3306/operation-platform-template
        #url: jdbc:mysql://127.0.0.1:3306/kar-operation-platform
        username: dev
        #username: root
        password: M20131209k
        #password: 123456
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        time-between-eviction-runs-millis: 18800 #就是这句话

      secondary:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        name: report
        jdbc-url: jdbc:mysql://10.10.13.125:3306/operation-platform
        #url: jdbc:mysql://127.0.0.1:3306/operation-platform
        username: dev
        #username: root
        password: M20131209k
        #password: 123456
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        time-between-eviction-runs-millis: 18800 #就是这句话

# https://blog.csdn.net/janceewa/article/details/79696949
    mongodb:
##        host: mongodb://admin:123456@localhost:27017/mongo_test
        host: mongodb://root:123456@10.20.222.63:27017/msg_center
        port: 27017
        username: root
        password: 123456
        database: msg_center
          #数据库 mongo_test 若不指定，默认打开 test 数据库

    redis:
        host: 10.30.0.234 #redis服务器地址
        #host: 127.0.0.1 #redis服务器地址
        port: 6379
        timeout: 10000 #超时时间
        database: 0 #0-15 16个库 默认0
        lettuce:
          pool:
            max-active: 8 #最大连接数
            max-wait: -1 #默认-1 最大连接阻塞等待时间
            max-idle: 8 #最大空闲连接 默认8
            min-idle: 0 #最小空闲连接
    rabbitmq:
      host: 10.20.222.62
      port: 5672
      username: guest
      password: guest
      timeout: 1000
      retryMaxCount: 5
      # 开启ACK
      listener:
        acknowledge-mode: manual


zookeeper:
  server: 10.20.222.77:2181,10.20.222.76:2181,10.20.222.75:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 6000
  maxRetries: 3
  baseSleepTimeMs: 1000


#kafka:
#  bootstrap-servers: 10.20.222.66:9092,10.20.222.67:9092
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




url:
   AULBUM_URL: http://10.20.222.150:8888/data-manage/manage/child/v1/album/findByPage

logging:
  config: classpath:log4j2.yml

#logging:
#    path: /logs
#    level:
#      all: debug
#      org.springframework : DEBUG
#      org.mybatis: DEBUG
#      java.sql.Connection: DEBUG
#      java.sql.Statement: DEBUG
#      java.sql.PreparedStatement: DEBUG

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0


