 
server:
  port: 8080
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  connection-timeout: 30
   
logging:
    path: /Users/logs
    level: 
      all: debug
      org.springframework : DEBUG
      org.mybatis: DEBUG
      java.sql.Connection: DEBUG
      java.sql.Statement: DEBUG
      java.sql.PreparedStatement: DEBUG
     
    
